# Generated by Django 3.2.9 on 2021-11-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='adoption_date',
        ),
    ]
